name: agriqr
description: 'Aplicación de trazabilidad agrícola con códigos QR'
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: any
  firebase_storage: ^12.4.9
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  permission_handler: ^11.3.0
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/agricultor.png
    - assets/client.png
    - assets/market.jpg
    - assets/qrcode.png
    - assets/app_icon.png
